---
info:
  component: Single Swagger Documentation UI for MicroServices.

spring:
  profiles: default

server:
  port: 8014

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

eureka:
  client:
    serviceUrl:
      defaultZone: ${swagger.baseurl}:8012/eureka/
    healthcheck:
      enabled: true

nh: 
  cos: 
    swagger: 
      baseurl: http://localhost
      services: 
        ms1: 
          url: ${swagger.baseurl}:8040/v2/api-docs?group=ms1
        ms2: 
          url: ${swagger.baseurl}:8050/v2/api-docs?group=ms2

